<?php if(count($this->getStores())>1): ?>
<div class="form-language">
    <label for="select-language">
        <select id="select-language" title="<?php echo $this->__('Your Language') ?>" onchange="window.location.href=this.value" class="<?php echo $addclass=strtolower(Mage::app()->getStore()->getName());?>">
        <?php foreach ($this->getStores() as $_lang): ?>
            <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? ' selected="selected"' : '' ?>
            <option value="<?php echo $_lang->getCurrentUrl() ?>" style="background-image:url('<?php echo $this->getSkinUrl('images/flags/flag_'.$_lang->getCode().'.png') ?>');"<?php echo $_selected ?>><?php echo $this->escapeHtml($_lang->getName()) ?></option>
        <?php endforeach; ?>
        </select>
    </label>
</div>
<?php endif; ?>
